export type { WorkerDTO } from './api/types'
export { workerSchema } from './api/types'
export { WorkerInfo } from './ui/WorkerInfo'
export { workerReducer, setWorkerData } from './model/slice'
export { selectWorkerData } from './model/selectors' 