export const mockUserData = {
  organizationId: "org-123",
  organizationName: "ООО Бюро 1440",
  departmentId: "dep-456",
  departmentName: "IT Отдел",
  outerId: "out-789",
  userId: "user-101",
  userADLogin: "ivanov",
  email: "ivanov@example.com",
  positionName: "Старший разработчик",
  positionId: "pos-202",
  lastName: "Иванов",
  firstName: "Иван",
  middleName: "Иванович",
  phone: "+7 (495) 123-45-67",
  dateHire: "2023-01-01",
  dateFire: null,
  dateBirth: "1990-01-01",
  website: "https://1440.space/"
} 